name: Check

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run check
        uses: gradle/gradle-build-action@v2.10.0
        with:
          arguments: check
