name: Check

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run check
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: check
