name: Check

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Run check
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: check
