name: Check

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Run check
        uses: gradle/gradle-build-action@v3.3.2
        with:
          arguments: check
