name: Check

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          validate-wrappers: true
      - name: Run check
        run: ./gradlew check
